const publishRelease = require('publish-release')
const exec = require('child_process').exec

// Get the latest tags just generated by semantic release from github

exec('git fetch', function (err, stdout) {
  if (err) throw err

      // Get latest tag
  exec('git tag', function (err, stdout) {
    if (err) throw err

    const tags = stdout.split('\n').filter(function (tag) { return tag !== '' }).reverse()
    const latestTag = tags[0]

        // Run publishRelease
    publishRelease({
      token: process.env.GH_TOKEN,
      owner: 'ConsenSys',
      repo: 'uport-connect',
      tag: latestTag,
      name: 'uport-connect',
      notes: '',
      reuseRelease: true,
      assets: ['dist/uport-connect.js', 'dist/uport-connect.js.map', 'dist/uport-connect.min.js', 'dist/uport-connect.min.js.map']
    }, function (err, release) {
      if (err) process.exit(1)
      process.exit(0)
    })
  })
})
