const publishRelease = require('publish-release')
const exec = require('child_process').exec

// Get the latest tags just generated by semantic release from github

exec('git pull', function (err, stdout) {
      if (err) throw err

      // Get latest tag
      exec('git tag', function (err, stdout) {
        if (err) throw err

        const tags = stdout.split('\n').filter(function (tag) { return tag !== '' }).reverse()
        const latestTag = tags[0]

        // Run publishRelease
        publishRelease({
          token: $GH_TOKEN,
          owner: 'ConsenSys',
          repo: 'uport-lib',
          tag: latestTag,
          name: 'uport-lib',
          notes: '',
          reuseRelease: true,
          assets: ['dist/uportlib.js', 'dist/uportlib.js.map', 'dist/uportlib.min.js', 'dist/uportlib.min.js.map'],
        }, function (err, release) {
          if (err) process.exit(1);
          process.exit(0);
        })
    })
})
