#!/bin/bash
# Script to setup tests against the npm package (not only the files)

cd ..
cp ./test/uport.js integration-test/
cp ./test/karma.conf.js integration-test/
cp ./test/testData.json integration-test/
npm pack
cd integration-test
npm install
