#!/bin/bash
# Script to setup tests against the npm package (not only the files)

cd ..
cp ./test/Connect.js ./test/karma.conf.js ./test/data.json package-test/
mv `npm pack | tail -n 1` uport-connect.tgz
cd package-test
npm install
